# -*- coding: utf-8 -*-
"""pandasLessons.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19tkoyhneNKWNiOcngwwC0dqDiYfw46rm

##Pandas

##Series
"""

import pandas as pd
import numpy as np
from numpy.random import randn

# Creating data examples
labels = ['a','b','c'] 
my_data = [10,20,30]
arr = np.array(my_data) 
d = {'a':10, 'b':20, 'c':30}

# Creating a series
# Hit tab when writing the series if you want to see syntax
# pd.Series(data=my_data) # output will actually display indicies and values 
# you can pass in python lists, np arrays, dictionaries, and pretty much almost any kind of data object

# With panda series, you can specify what you want index to be
# setting indicies with variable label contents
pd.Series(data=my_data,index=labels) 
# can write like this too: pd.Series(my_data,labels)

# you can pass in python lists, np arrays, and dictionaries

# passing a dictionary will automatically grab the keys
# key will be index, and value will be value
pd.Series(d)

# You can pass in built in functions 
pd.Series(data=[sum,print,len]) # gives you references to the actual functions- something you cannot do with numpys

# Grabbing information from a series 

# creating pd series
                # data    , indicies
ser1 = pd.Series([1,2,3,4],['USA','Germany','USSR','Japan'])
# ser2 = pd.Series([1,2,5,4],['USA','Germany','Italy','Japan'])  

# Grabbing info ex 1
# same as indexing in python, just type index you want
# ser1['USA'] 

# creating a series with data as labels
# ser3 = pd.Series(labels)

# Grabbing info ex 1
# ser3[0]
# ser1

"""##DataFrames"""

# Seed ensures we get the same random numbers
np.random.seed(101)

# Creating a dataframe with random data
# Don't forget to press tab after the item you want to see the syntax for
df = pd.DataFrame(randn(5,4),['A','B', 'C', 'D', 'E'], ['W','X','Y','Z'])
df